# Copyright (C) 2024 Nastro_
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

FROM python:3.12.6-alpine3.20

ENV PORT=8000

ENV BUILD="false"

WORKDIR /gestionale

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE ${PORT}

RUN chmod a+x ./startup.sh

CMD ["/bin/sh", "-c", "./startup.sh"]
