# Generated by Django 4.2.16 on 2024-10-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
