# Generated by Django 4.2.16 on 2024-10-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0004_ticket_id_user_in_charge_alter_ticket_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='prev_product_detail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='product_detail',
            field=models.TextField(null=True),
        ),
    ]
