# Generated by Django 4.2.16 on 2024-10-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0005_alter_record_prev_product_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
