# Generated by Django 4.2.16 on 2024-10-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0006_alter_bundle_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
