# Generated by Django 4.2.16 on 2024-10-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionale', '0007_accessory_is_deleted_computer_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
